services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10

  backend:
    image: ghcr.io/valenboiero03/mi-backend:v0.1.0
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD}@db:5432/app"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ghcr.io/valenboiero03/mi-frontend:v0.1.0
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: